services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: kmg1_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: strong_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
